### ISSUE TITLE
Cannot MONIT_Silver Pure

### ISSUE THREAD

**Issue by jeffmilton** [Jericho1060/DU-Industry-HUD#17]
Cannot MONIT_ a container with "Silver Pure" because the hud is looking for Pure Silver. Honestly, I prefer it to display as Silver Pure to make it easier to find alphabetically, but the hud should take "MONIT_Silver Pure" or "MONIT_Pure Silver" because it's called Silver Pure in the game.

**Comment by thoda-dev** [comment]
This is not really a bug as it's an wrong name of item in game.
All pure material in game should be named `Pure Material`.

Unfortunately, some are wronglike Silver but also Nickel that are named `Material pure` this is translation mistake from and should be fixed in game later. Due to that, i won't changed it on my list.

Please, for all pure materials, use `Pure Material_name` as template for the moment, i'll upgrade later my search function to find both versions of the name to avoid any other problem.
