### ISSUE TITLE
container monitoring

### ISSUE THREAD

**Issue by thoda-dev** [Jericho1060/DU-Industry-HUD#4]
monitoring containers items quantity

**Comment by afinegan** [comment]
I have some code for this - based on preset knowledge of weights of items and the containers ONLY have that 1 item in there, you can pull the weight and divide to figure out the amount in the container - my code for this needs some updating first though since all the ore container readers were pulling info from the static core, when I should just forward the minimal information to the databank and only have the main computer pull the information from the element core

**Comment by thoda-dev** [comment]
yes i know how to do it :D
i'm using it on an other HUD, i just want to integrate everything on the same HUD and do not use 2 differents :D 
i don't need to store any data coming from the container or event to link any container to a board, i can get everything from the core

**Comment by thoda-dev** [comment]
1st version deployed
only the master program needs an update
no links required
see the documentation to know how to enable containers or hubs

**Comment by thoda-dev** [comment]
new update deployed with fill gauge for containers
![unknown](https://user-images.githubusercontent.com/28439359/97104905-a059d480-16b7-11eb-8159-064726fbe3ca.png)
